#!/bin/bash

if [ -z "$1" ]
    then
        echo "container tag missing"
        exit 1
fi

cd $HOME/git/voltha-northbound-bbf-adapter
DOCKER_REGISTRY="$USER/" DOCKER_TAG="$1" make docker-build
kind load docker-image $USER/voltha-northbound-bbf-adapter:$1
