#!/bin/bash

cd $HOME/kind-cfg
kind delete cluster
kind create cluster --config 3-node-cfg.yaml
kubectl taint nodes --all node-role.kubernetes.io/master-
kind get kubeconfig > $HOME/.kube/config

#Start deploying infra, which takes a long time to complete
helm upgrade --install --create-namespace -n infra voltha-infra onf/voltha-infra --set onos-classic.image.tag=master
