#!/bin/bash

#Kill old commands
ps -ao pid,args | grep port-forward | grep -v grep | awk '{print $1}' | ifne xargs kill

#Port forward
bash -c "while true; do kubectl port-forward -n infra svc/voltha-infra-onos-classic-hs 8101; done" &
bash -c "while true; do kubectl port-forward -n infra svc/voltha-infra-onos-classic-hs 8181; done" &
bash -c "while true; do kubectl -n voltha port-forward svc/voltha-voltha-api 55555; done" &
