#!/bin/bash

kind load docker-image lwc:latest
kind load docker-image docker-registry.com:5000/bitnami/redis:6.0.10-debian-10-r19

kubectl create configmap -n infra kube-config "--from-file=kube_config=$KUBECONFIG"

cd $HOME/lwc
helm upgrade --install --create-namespace -n infra --version 2.8.2 voltha-infra helm_charts/voltha-infra/