#!/bin/bash

if [ -z "$1" ]
    then
        echo "container tag missing"
        exit 1
fi

cd $HOME/git/voltha-go
DOCKER_REGISTRY="erap320/" DOCKER_TAG="$1" make docker-build
kind load docker-image erap320/voltha-rw-core:$1
helm upgrade --install --create-namespace \
	  -n voltha voltha onf/voltha-stack \
	  --set global.stack_name=voltha \
	  --set voltha_infra_name=voltha-infra \
	  --set voltha_infra_namespace=infra \
	  --set global.image_pullPolicy=Always \
	  --set global.image_tag=master \
	  --set global.log_level=DEBUG \
	  --set voltha.images.rw_core.repository=erap320/voltha-rw-core \
  	  --set voltha.images.rw_core.tag=$1 \
	  --set voltha.images.rw_core.pullPolicy=Never
