#!/bin/bash

if [ -z "$1" ]
    then
        echo "container tag missing"
        exit 1
fi

cd $HOME/git/bbsim
DOCKER_REGISTRY="$USER/" DOCKER_TAG="$1" make docker-build
kind load docker-image $USER/bbsim:$1
helm upgrade --install -n voltha bbsim0 onf/bbsim --set olt_id=10 \
--set images.bbsim.repository=$USER/bbsim,images.bbsim.tag=$1,images.bbsim.pullPolicy=Never
